#applicattion.properties와 같은 역활

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 100MB

  jpa:
    hibernate:
      #아래 옵션은 애플리케이션 실행 시점에 테이블을 drop 하고, 다시 생성한다
      ddl-auto: create
    properties:
      hibernate:
  # show_sql: true
        format_sql: true


#상품 이미지 업로드 경로
itemImgLocation: C:/shop/item

#리소스 업로드 경로
uploadPath: file:///C:/shop/

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace  #스프링 부트 3.x, hibernate6: 옵션은 logger를 통해 하이버네이트 실행 SQL을 남긴다.